In [1]:
import csv
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle

In [2]:
df = pd.read_csv('Training.csv')
df.head()

X1        X2        X3        X4        X5        X6        X7  \
0  0.189148  0.189148  0.189148  0.189148  0.177176  0.177176  0.174782   
1  0.174782  0.174782  0.174782  0.122108  0.122108  0.122108  0.126897   
2  0.256187  0.256187  0.256187  0.256187  0.284919  0.284919  0.260976   
3  0.158022  0.158022  0.158022  0.088588  0.088588  0.088588  0.112531   
4  0.253793  0.253793  0.253793  0.232245  0.232245  0.232245  0.225062   

         X8        X9       X10  ...       Z24       Z25       Z26       Z27  \
0  0.174782  0.174782  0.165205  ...  9.768641  9.768641  9.581888  9.581888   
1  0.126897  0.160416  0.160416  ...  9.811738  9.811738  9.512454  9.512454   
2  0.260976  0.268159  0.268159  ...  9.773430  9.773430  9.392740  9.392740   
3  0.112531  0.160416  0.160416  ...  9.830893  9.830893  9.466963  9.466963   
4  0.225062  0.203513  0.203513  ...  9.419077  9.419077  9.720756  9.720756   

        Z28       Z29       Z30       Z31       Z32  direction  
0  9.581888  9.610620  9.610620  9.742304  9.742304      Above  
1  9.689631  9.689631  9.830893  9.830893  9.830893      Above  
2  9.792584  9.792584  9.792584  9.799767  9.799767      Above  
3  9.725544  9.725544  9.845258  9.845258  9.845258      Above  
4  9.744699  9.744699  9.502876  9.502876  9.502876      Above  

[5 rows x 97 columns]

In [3]:
df.shape

(813, 97)

In [4]:
df.columns

Index(['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11',
       'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21',
       'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28', 'X29', 'X30', 'X31',
       'X32', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8', 'Y9', 'Y10',
       'Y11', 'Y12', 'Y13', 'Y14', 'Y15', 'Y16', 'Y17', 'Y18', 'Y19', 'Y20',
       'Y21', 'Y22', 'Y23', 'Y24', 'Y25', 'Y26', 'Y27', 'Y28', 'Y29', 'Y30',
       'Y31', 'Y32', 'Z1', 'Z2', 'Z3', 'Z4', 'Z5', 'Z6', 'Z7', 'Z8', 'Z9',
       'Z10', 'Z11', 'Z12', 'Z13', 'Z14', 'Z15', 'Z16', 'Z17', 'Z18', 'Z19',
       'Z20', 'Z21', 'Z22', 'Z23', 'Z24', 'Z25', 'Z26', 'Z27', 'Z28', 'Z29',
       'Z30', 'Z31', 'Z32', 'direction'],
      dtype='object')

In [5]:
df.direction.unique()

array(['Above', 'Right', 'Below', 'Left'], dtype=object)

In [6]:
train_samples = []
train_labels = []

no_of_features = 96
firstLine = True

with open('Training.csv') as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    for row in readCSV:
        if firstLine:
            firstLine = False
        else:
            list = []
            for i in range(0, no_of_features):
                list.append(float(row[i]))

            train_samples.append(np.array(list))
            train_labels.append(row[no_of_features])

In [7]:
encoder = LabelBinarizer()
transfomed_label = encoder.fit_transform(train_labels)

train_samples = np.array(train_samples)
train_labels = np.array(transfomed_label)

In [8]:
print(train_samples)
print(train_labels)

[[0.18914771 0.18914771 0.18914771 ... 9.61061954 9.74230385 9.74230385]
 [0.17478207 0.17478207 0.17478207 ... 9.83089256 9.83089256 9.83089256]
 [0.25618741 0.25618741 0.25618741 ... 9.79258442 9.79976654 9.79976654]
 ...
 [0.1699935  0.1699935  0.1699935  ... 9.67526436 9.67526436 9.67526436]
 [0.18196489 0.18196489 0.18196489 ... 9.5866766  9.7039957  9.57949352]
 [0.20111908 0.20111908 0.20111908 ... 9.73512173 9.74948692 9.74948692]]
[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 ...
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]]


In [9]:
scaler = MinMaxScaler(feature_range=(-1,1))
scaled_train_samples = (scaler.fit_transform(train_samples))

In [10]:
scaled_train_samples, train_labels = shuffle(scaled_train_samples, train_labels, random_state=0)
print(scaled_train_samples)
print(train_labels)

[[-0.01562502 -0.01562502 -0.01562502 ...  0.37327367  0.24651197
   0.23222686]
 [ 0.09375004  0.09375004  0.09375004 ...  0.06912679  0.45116391
   0.44075872]
 [-0.03125001 -0.03125001 -0.03125001 ...  0.38248812  0.25581214
   0.24170335]
 ...
 [ 0.51562508  0.51562508  0.51562508 ... -0.29032151 -0.42325599
  -0.45023899]
 [-0.09374999 -0.09374999 -0.09374999 ...  0.31797223  0.19069612
   0.17535282]
 [ 0.12500003  0.12500003  0.12500003 ...  0.23502375  0.6372081
   0.63033005]]
[[0 0 1 0]
 [1 0 0 0]
 [1 0 0 0]
 ...
 [0 0 1 0]
 [0 1 0 0]
 [0 0 1 0]]


In [11]:
model = Sequential([
    Dense(64, input_shape=(96,), activation='relu'),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(4, activation='softmax')
])



In [12]:
model.summary()
model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(scaled_train_samples, train_labels, validation_split = 0.1, batch_size=10, epochs=150, shuffle=True, verbose=2)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                6208      
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_3 (Dense)              (None, 4)                 260       
Total params: 14,788
Trainable params: 14,788
Non-trainable params: 0
_________________________________________________________________
Epoch 1/150
74/74 - 5s - loss: 1.2432 - accuracy: 0.4624 - val_loss: 0.9759 - val_accuracy: 0.7805
Epoch 2/150
74/74 - 0s - loss: 0.7875 - accuracy: 0.7360 - val_loss: 0.6554 - val_accuracy: 0.7805
Epoch 3/150
74/74 - 0s - loss: 0.5153 - accuracy: 0.

Epoch 73/150
74/74 - 0s - loss: 6.8855e-05 - accuracy: 1.0000 - val_loss: 0.6219 - val_accuracy: 0.9268
Epoch 74/150
74/74 - 0s - loss: 6.6107e-05 - accuracy: 1.0000 - val_loss: 0.6211 - val_accuracy: 0.9268
Epoch 75/150
74/74 - 0s - loss: 6.3009e-05 - accuracy: 1.0000 - val_loss: 0.6312 - val_accuracy: 0.9268
Epoch 76/150
74/74 - 0s - loss: 5.9843e-05 - accuracy: 1.0000 - val_loss: 0.6317 - val_accuracy: 0.9268
Epoch 77/150
74/74 - 0s - loss: 5.6277e-05 - accuracy: 1.0000 - val_loss: 0.6330 - val_accuracy: 0.9268
Epoch 78/150
74/74 - 0s - loss: 5.3695e-05 - accuracy: 1.0000 - val_loss: 0.6364 - val_accuracy: 0.9268
Epoch 79/150
74/74 - 0s - loss: 5.1653e-05 - accuracy: 1.0000 - val_loss: 0.6397 - val_accuracy: 0.9268
Epoch 80/150
74/74 - 0s - loss: 4.8119e-05 - accuracy: 1.0000 - val_loss: 0.6422 - val_accuracy: 0.9268
Epoch 81/150
74/74 - 0s - loss: 4.6065e-05 - accuracy: 1.0000 - val_loss: 0.6455 - val_accuracy: 0.9268
Epoch 82/150
74/74 - 0s - loss: 4.4025e-05 - accuracy: 1.0000 - 

In [13]:
_,accuracy = model.evaluate(scaled_train_samples,train_labels)
print('Accuracy: %.2f' %(accuracy*100))

26/26 [==============================] - 0s 1ms/step - loss: 0.0828 - accuracy: 0.9914
Accuracy: 99.14


### Observations:


The dataset is about the values of x,y,z axes with 'Direction' as the target variable. The predicting labels are X1, X2,...X32 and likewise Y1,Y2 ....Y32 and Z1,Z2,Z3,......Z32

We process the csv data to array datatype and fit it into MultiLayer Perceptron model using keras API. 
Training_samples array has predicting variables and train_labels has 4 directions encoded( for 'RIGHT', [0 1 0 0]).

We create keras model with 5 layers:
1. Input layer : 96
2. 1st hidden layer: 64, activation: relu
3. 2nd hidden layer: 64, activation: relu
4. 3rd hidden layer: 64, activation: relu
5. Output layer: 4, activation: softmax

We see that for 150 epochs, adam optimizer, we get accuracy of 99.38%. 